import type { CommentProvider, GeneratedTest } from './types.js';

export function formatPrComment(tests: GeneratedTest[]): string {
  const lines: string[] = [
    '<!-- natl-agent -->',
    '## NATL Agent — suggested tests',
    '',
  ];

  if (!tests.length) {
    lines.push('_No tests generated (no actionable semantic changes)._');
    return lines.join('\n');
  }

  for (const t of tests) {
    let status = t.validationOk ? 'passed `natl validate`' : 'failed validation';
    if (t.healed) status = 'passed `natl validate` after self-healing';
    lines.push(`### \`${t.fileName}\` (${status})`);
    if (t.validationError) {
      lines.push('', `> ${t.validationError}`, '');
    }
    if (t.normalizeFixes?.length) {
      lines.push('', 'Deterministic normalize:');
      for (const f of t.normalizeFixes) {
        lines.push(`- ${f}`);
      }
      lines.push('');
    }
    if (t.healAttempts?.length) {
      lines.push('', 'Self-healing history:');
      for (const h of t.healAttempts) {
        lines.push(`- attempt ${h.attempt} (${h.kind}): ${h.error}`);
      }
      lines.push('');
    }
    if (t.uir.length) {
      lines.push(
        '',
        'Changes:',
        ...t.uir.map(
          (u) => `- **${u.changeType}** \`${u.entity}\` in \`${u.file}\` (${u.risk})`,
        ),
        '',
      );
    }
    lines.push('```yaml', t.yaml.trim(), '```', '');
  }

  lines.push(
    '---',
    '_Generated by `@natl/agent` via OpenAI-compatible API. Review before applying._',
  );
  return lines.join('\n');
}

export interface PublishOptions {
  mode: 'comment' | 'stdout' | 'commit';
  body: string;
  /** Backend for mode=comment. Default auto. */
  commentProvider?: CommentProvider;
  githubToken?: string;
  githubRepo?: string; // owner/repo
  githubPrNumber?: number;
  gitlabToken?: string;
  /** API v4 root, no trailing slash. */
  gitlabApiUrl?: string;
  gitlabProjectId?: string;
  gitlabMrIid?: number;
  fetchImpl?: typeof fetch;
}

export function resolveCommentProvider(opts: PublishOptions): CommentProvider {
  const requested = opts.commentProvider ?? 'auto';
  if (requested !== 'auto') return requested;

  const canGitlab =
    Boolean(opts.gitlabToken) &&
    Boolean(opts.gitlabProjectId) &&
    opts.gitlabMrIid != null;
  if (canGitlab) return 'gitlab';

  const canGithub =
    Boolean(opts.githubToken) &&
    Boolean(opts.githubRepo) &&
    opts.githubPrNumber != null;
  if (canGithub) return 'github';

  return 'stdout';
}

async function publishGithubComment(opts: PublishOptions): Promise<{
  published: boolean;
  message: string;
}> {
  const token = opts.githubToken;
  const repo = opts.githubRepo;
  const pr = opts.githubPrNumber;
  if (!token || !repo || pr == null) {
    return {
      published: false,
      message:
        'GitHub comment skipped (need GITHUB_TOKEN, github repo, and PR number). Body:\n\n' +
        opts.body,
    };
  }

  const fetchImpl = opts.fetchImpl ?? fetch;
  const url = `https://api.github.com/repos/${repo}/issues/${pr}/comments`;
  const res = await fetchImpl(url, {
    method: 'POST',
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ body: opts.body }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub comment failed HTTP ${res.status}: ${text.slice(0, 400)}`);
  }
  return { published: true, message: `Commented on GitHub PR #${pr}` };
}

async function publishGitlabNote(opts: PublishOptions): Promise<{
  published: boolean;
  message: string;
}> {
  const token = opts.gitlabToken;
  const projectId = opts.gitlabProjectId;
  const mrIid = opts.gitlabMrIid;
  const api = (opts.gitlabApiUrl ?? 'https://gitlab.com/api/v4').replace(/\/+$/, '');

  if (!token || !projectId || mrIid == null) {
    return {
      published: false,
      message:
        'GitLab note skipped (need GITLAB_TOKEN / CI_JOB_TOKEN, project id, and MR IID). Body:\n\n' +
        opts.body,
    };
  }

  const fetchImpl = opts.fetchImpl ?? fetch;
  const encoded = encodeURIComponent(projectId);
  const url = `${api}/projects/${encoded}/merge_requests/${mrIid}/notes`;
  const res = await fetchImpl(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'PRIVATE-TOKEN': token,
      // Job tokens also accept Bearer on some GitLab versions
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ body: opts.body }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitLab note failed HTTP ${res.status}: ${text.slice(0, 400)}`);
  }
  return {
    published: true,
    message: `Commented on GitLab MR !${mrIid} (project ${projectId})`,
  };
}

/**
 * Publish agent output: stdout/commit → log body;
 * comment → GitHub PR comment, GitLab MR note, or stdout fallback.
 */
export async function publishResult(opts: PublishOptions): Promise<{
  published: boolean;
  message: string;
}> {
  if (opts.mode === 'stdout' || opts.mode === 'commit') {
    return { published: false, message: opts.body };
  }

  const provider = resolveCommentProvider(opts);

  if (provider === 'stdout') {
    return {
      published: false,
      message:
        'Comment provider=stdout (no GitHub/GitLab credentials detected). Body:\n\n' +
        opts.body,
    };
  }

  if (provider === 'gitlab') {
    return publishGitlabNote(opts);
  }

  return publishGithubComment(opts);
}
