title: NATL
description: Short open-source YAML runner for web UI and API tests
theme: jekyll-theme-primer
url: https://arslan-ahmetjanov.github.io
baseurl: /natl
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
